// <auto-generated />
using Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasMaxLength(10);

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar")
                        .HasMaxLength(80);

                    b.Property<string>("Estado")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("NumeroImovel")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasMaxLength(10);

                    b.Property<string>("Rua")
                        .HasColumnType("varchar")
                        .HasMaxLength(100);

                    b.Property<string>("TipoImovel")
                        .HasColumnType("varchar")
                        .HasMaxLength(100);

                    b.Property<string>("Valor")
                        .HasColumnType("varchar")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Catalogos");
                });
#pragma warning restore 612, 618
        }
    }
}
